### ISSUE TITLE
Invoke `lsb-release` directly

### ISSUE THREAD

**Issue by vladimyr** [rhysd/node-ubuntu-version#1]
https://github.com/rhysd/node-ubuntu-version/blob/64a590d4a0dba4b96ca08cadbed51fbbdfbbff46/index.ts#L12

Avoid spawning a new shell and just invoke the target directly using [`execFile`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) instead:

> The `child_process.execFile()` function is similar to `child_process.exec()` except that it does not spawn a shell by default. Rather, the specified executable file is spawned directly as a new process making it slightly more efficient than `child_process.exec()`.

**Comment by rhysd** [comment]
Nice catch:+1:. I will try it today.

**Comment by vladimyr** [comment]
Btw, an example of prior art https://github.com/mmalecki/lsb-release 😉
